### ISSUE TITLE
Authenticating via Service Account Key JSON does not work

### ISSUE THREAD

**Issue by SeriyBg** [google-github-actions/auth#73] opened 2021-12-06 09:52 UTC
### TL;DR

Moving from deprecated `service_account_key` in the `google-github-actions/setup-gcloud` to the `credentials_json` gives me the following error: 
```
Error: google-github-actions/setup-gcloud failed with: Error parsing credentials: Unexpected end of JSON input
Ensure your credentials are base64 encoded or validate JSON format: 
```

I have also tried to encode the JSON key to `base64` but it does not change the behaviour

### Action YAML

```yaml
name: Test on GKE
on:
  push: {}

env:
  PROJECT_ID: my-project
  GKE_ZONE: europe-west1-b

jobs:
  create-e-cluster:
    name: Create GKE cluster
    runs-on: ubuntu-latest
    outputs:
      cluster_name: my-cluster

    steps:
    # Setup gcloud CLI
    - id: 'auth'
      uses: 'google-github-actions/auth@v0.4.1'
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
    - uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true
```

### Additional information

It's not the issue with the JSON key itself, as the same value for the `service_account_key` in the `google-github-actions/setup-gcloud` is working.

**Comment by Ganitzsh** [comment] 2021-12-06 09:58
I can confirm this, same issue on our CI

**Comment by sethvargo** [comment] 2021-12-06 15:14
Hi @Ganitzsh 

Thank you for opening an issue. This error is coming from https://github.com/google-github-actions/setup-cloud-sdk (/cc @bharathkkb).

We're going to need some time to investigate and reproduce this.

Note that you don't need `export_default_credentials` on setup-gcloud if you use `auth`; `auth` automatically exports the credentials. That's not the issue here, just an FYI.

**Comment by Claker** [comment] 2021-12-06 15:31
When I now move to `google-github-actions/setup-gcloud@master` I get same issue as the rest of you.
I guess it is not recommended to use @master... but @v0.2.1 for example.

**Comment by sethvargo** [comment] 2021-12-06 22:15
@Clarker - can you please share your complete GitHub Actions YAML?

**Comment by sethvargo** [comment] 2021-12-06 23:18
I'm a little confused because we have the exact setup in the provided YAML in our [test suite](https://github.com/google-github-actions/auth/blob/ed829381c8f1cb12cbd2675ab952e1b584422fbf/.github/workflows/test.yaml#L89-L97), which is [currently passing](https://github.com/google-github-actions/auth/runs/4437395485).

I think this might have been fixed with the recent upgrade of a dependency in `setup-gcloud@master`. If it's still not working for you, please comment and I'll re-open this issue.

**Comment by bharathkkb** [comment] 2021-12-06 23:25
@sethvargo I think there is a bug in setup-gc. We parse and export like https://github.com/google-github-actions/setup-gcloud/blob/41d62c9cff656349e643d2d59ec4c8840c98bc97/src/setup-gcloud.ts#L103 but `serviceAccountKey` maybe empty if auth is in env var `GOOGLE_GHA_CREDS_PATH`. The test is this repo bypassed the codepath due to `export_default_credentials` not being set.

**Closed** 2021-12-22 17:10 UTC
Labels: bug

**Comment by victorlimadesco** [comment] 2024-09-25 11:02
Hi everyone!

I resolved this issue changing my credentials for base64. Bellow I share the command and step to Gitactions.

Command: cat path/to/credentials.json | base64

Step Gitactions Workflows: 

    - name: Authenticate with GCP
      run: |
        echo "${{ secrets.GCP_CREDENTIALS }}" | base64 --decode > "${HOME}/gcp-key.json"
        
        # Exibir o conteúdo do arquivo para verificação
        echo "Verificando o conteúdo do arquivo JSON:"
        cat "${HOME}/gcp-key.json"
        
        # Definir a variável de ambiente
        export GOOGLE_APPLICATION_CREDENTIALS="${HOME}/gcp-key.json"
        
        # Tentar autenticar
        gcloud auth activate-service-account --key-file="${HOME}/gcp-key.json"
