### ISSUE TITLE
Unable to authenticate for gcloud alpha storage

### ISSUE THREAD

**Issue by louisadamian** [google-github-actions/auth#120] opened 2022-01-31 18:48 UTC
### TL;DR

When trying to use gcloud alpha storage to download from a bucket after running auth with Workload Identity Federation and setup-gcloud I get an authentication error. When running the same command locally with key authentication I do not get the error.

### Expected behavior

gcloud downloads the file from my bucket

### Observed behavior

Authentication error

### Action YAML

```yaml
name: Docker Build

on:
  push:
    branches: [ main, dev/main ]
  pull_request:
    branches: [ main, dev/main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GAR_LOCATION: us-central1
  REPOSITORY: aemotrics
  IMAGE: aemotrics_predict

jobs:
  docker-build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
        service_account: ${{ secrets.GCP_SA }}
    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: install deps
      run: sudo python3 -m pip install google-crc32c --target /opt/hostedtoolcache/gcloud/370.0.0/x64/lib/third_party && sudo python3 -m pip install build && gcloud --quiet auth list
    - name: Get Model
      run: gcloud --quiet alpha storage cp gs://aemotrics_models/Aemotrics_V3-Nate-2021-12-20_pruned.tar.gz ./microservice
    - name: Build Aemotrics Wheel
      run: python3 -m build -w && mkdir microservice/wheel && cp dist/* microservice/wheel/
    - name: Build the Docker image
      run: docker build microservice --tag "$IMAGE:$GITHUB_SHA"
    - name: Publish
      run: |-
        docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA"
```

### Log output

```text
There was a problem refreshing your current auth tokens: ('Unable to acquire impersonated credentials: No access token or invalid expiration in response.', '{\n  "error": {\n    "code": 403,\n    "message": "The caller does not have permission",\n    "status": "PERMISSION_DENIED"\n  }\n}\n')
```

### Additional information

when running the same command on my local machine from the same service account with key authentication I do not get the error.

**Comment by sethvargo** [comment] 2022-01-31 19:50
How have you configured Workload Identity Federation?

**Comment by louisadamian** [comment] 2022-02-02 14:23
yes, and it was working before it just stopped working, without changing the action yaml.

**Comment by sethvargo** [comment] 2022-02-03 00:16
The error message makes me think something has changed with your Workload Identity Federation configuration. How is WIF configured? What are your Attribute Mappings? What are your Attribute Conditions? What principal set is configured to impersonate the Service Account?

On which step are you getting that error message?

**Comment by louisadamian** [comment] 2022-02-03 16:52
I get the error message when I run `gcloud --quiet alpha storage cp`. My attribute mappings are attribute.actor : assertion.actor, google.subject: assertion.sub, attribute.repository : assertion.repository. I have no attribute conditions. and the principal set is configured for a service account that I know has access to the bucket I am trying to access.

**Comment by sethvargo** [comment] 2022-02-03 16:57
What principal set is configured to impersonate the Service Account and what is the service account? You should have a service account with `Workload Identity User` permissions granted to something that looks like `principalSet://...`.

**Comment by louisadamian** [comment] 2022-02-03 17:28
Yes it's `principalSet://iam.googleapis.com/projects/****/locations/global/workloadIdentityPools/****/attribute.repository/SurgicalPhotonics/Aemotrics`

**Comment by sethvargo** [comment] 2022-02-03 17:39
Can you try some of the troubleshooting steps listed [here](https://github.com/google-github-actions/auth/blob/main/docs/TROUBLESHOOTING.md#troubleshooting)? It's generally very difficult for us to debug these kinds of issues, since we don't have access to the environment.

**Comment by louisadamian** [comment] 2022-02-03 18:04
I changed the auth step 
```yaml
- id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
        service_account: ${{ secrets.GCP_SA }}
        token_format: 'access_token'
```
and then I got the error `
google-github-actions/auth failed with: failed to generate Google Cloud access token for ***: {
[20](https://github.com/SurgicalPhotonics/aemotrics/runs/5055951311?check_suite_focus=true#step:3:20)
  "error": {
[21](https://github.com/SurgicalPhotonics/aemotrics/runs/5055951311?check_suite_focus=true#step:3:21)
    "code": 403,
[22](https://github.com/SurgicalPhotonics/aemotrics/runs/5055951311?check_suite_focus=true#step:3:22)
    "message": "The caller does not have permission",
[23](https://github.com/SurgicalPhotonics/aemotrics/runs/5055951311?check_suite_focus=true#step:3:23)
    "status": "PERMISSION_DENIED"
[24](https://github.com/SurgicalPhotonics/aemotrics/runs/5055951311?check_suite_focus=true#step:3:24)
  }
[25](https://github.com/SurgicalPhotonics/aemotrics/runs/5055951311?check_suite_focus=true#step:3:25)
}
`

**Comment by sethvargo** [comment] 2022-02-03 19:20
That indicates that something is invalid in your WIF configuration. Again, without access to the environment, it's _very_ difficult to debug. You could try enabling WIF audit logging and seeing if there's any helpful logs in GCP.

The error message tells me that the service account impersonation is failing, so I would encourage you to check the principalSet and make sure the token claims match what you're expecting.

**Comment by louisadamian** [comment] 2022-02-04 21:14
Ok, for some reason even after adding Service Account Token Creator to my principalSet permissions on the service account page.

**Comment by louisadamian** [comment] 2022-02-04 22:43
I create a new WIF pool and provider and a new service account using this https://github.com/google-github-actions/auth#setting-up-workload-identity-federation guide. and I get the error
"error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED"
  }

**Comment by sethvargo** [comment] 2022-02-05 15:43
Hi @louisadamian 

Without incredibly detailed information including the exact commands you ran, it's nearly impossible to help debug. Also note that the creation/changing of any WIF properties are eventually consistent and can take up to 5min to propagate.

**Comment by enocom** [comment] 2022-02-10 02:08
For what it's worth, I had a similar 403 error and found this thread. The problem in my case was a mismatch with the `attribute-mapping` in my OIDC provider configuration and the `principalSet` used in the IAM binding with my associated service account.

When I changed the `principalSet` to be more open like so `principalSet://iam.googleapis.com/<pool-id>/*`, the error disappeared and this action worked as expected.

**Comment by sethvargo** [comment] 2022-02-10 02:26
@enocom I'd be very careful with that. Without any attribute _conditions_ on the providers, that will allow _any_ GitHub repo permission to access your project and impersonate any service accoun.t

**Comment by enocom** [comment] 2022-02-10 04:37
:sweat_smile: That's good to know. I'll restore an attribute condition of the repo name at least.

**Comment by enocom** [comment] 2022-02-10 05:44
Having spent another round with this, I've found it's just way too easy to misconfigure WIF. I found the simplest approach was to just use the [Terraform module](https://github.com/terraform-google-modules/terraform-google-github-actions-runners/tree/master/modules/gh-oidc), which worked without issue.

**Comment by ethanmdavidson** [comment] 2022-02-17 16:38
> Yes it's `principalSet://iam.googleapis.com/projects/****/locations/global/workloadIdentityPools/****/attribute.repository/SurgicalPhotonics/Aemotrics`

> and then I got the error `google-github-actions/auth failed with: failed to generate Google Cloud access token for ***: { [20](https://github.com/SurgicalPhotonics/aemotrics/runs/5055951311?check_suite_focus=true#step:3:20) "error": { [21]...`

The attribute conditions are case sensitive, and it looks like maybe WIF is being configured with a capital A when it should be lowercase? 

Also fwiw the authentication works fine for me with `gcloud alpha storage`, so I really don't think that's where the problem is. Maybe also try a different gcloud command and see if that works?

**Comment by louisadamian** [comment] 2022-03-08 20:52
The issue was never resolved, but I am no longer working on trying to fix it.

**Comment by sethvargo** [comment] 2022-03-08 21:06
Okay thanks @louisadamian. Since there's not additional information available to debug this, I'm going to go ahead and close it. If you resume working on this project, we can definitely re-open and try to get to the bottom of it.

**Closed by sethvargo** 2022-03-08 21:06 UTC
Labels: bug, waiting-response
