### ISSUE TITLE
Document and/or support authentication for gsutil

### ISSUE THREAD

**Issue by gpoulin-hopper** [google-github-actions/auth#49] opened 2021-11-18 15:16 UTC
### TL;DR

I want to be able to use gsutil within github action using Workload Identity Federation for authentication.

### Detailed design

The readme says how to configure gcloud using Workload Identity Federation. However it specifically outline that this method won't work for gsutil and doesn't provide alternative. The google-github-actions/upload-cloud-storage action can be used as a replacement but its functionality is limited compared to gsutil.

ref.: https://github.com/google-github-actions/auth#configuring-gcloud

**Comment by sethvargo** [comment] 2021-11-18 16:14
Duplicate of #28 - please file feedback with the Cloud SDK team via `gcloud feedback` or use the `gcloud alpha storage` commands. Unfortunately there's nothing we can do inside this GitHub Action to make it work with gsutil as gsutil needs to add support for Workload Identity Federation.

**Closed by sethvargo** 2021-11-18 16:14 UTC
Labels: enhancement

**Comment by gpoulin-hopper** [comment] 2021-11-18 16:59
Should the readme be updated to mention `gcloud alpha storage` as an alternative for the moment?
